# fly.toml app configuration file generated for trej-book-backend-empty-darkness-9295 on 2024-01-31T18:09:52-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trej-book-backend-empty-darkness-9295"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
